apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service1.name }}  
spec:
  type: {{ .Values.service1.type }}
  ports:
    - port: {{ .Values.service1.port }}
      targetPort: {{ .Values.app1.containerPort }}    
  selector:
    app: {{ .Values.app1.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service2.name }}  
spec:
  type: {{ .Values.service2.type }}
  ports:
    - port: {{ .Values.service2.port }}
      targetPort: {{ .Values.app2.containerPort }}     
  selector:
    app: {{ .Values.app2.name }}